## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/belgium/belgium_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004 entries, 0 to 2003
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           980 non-null    float64
 1   Name             2004 non-null   object
 2   Position         2004 non-null   object
 3   Date of Birth    2004 non-null   object
 4   Age              2003 non-null   object
 5   Nationality      2001 non-null   object
 6   Birth Country    2004 non-null   object
 7   Place of Birth   1666 non-null   object
 8   Height           1683 non-null   object
 9   Market Value     2004 non-null   object
 10  Other Positions  1329 non-null   object
 11  Nationality 1    2001 non-null   object
 12  Nationality 2    737 non-null    object
 13  Position 2       1329 non-null   object
 14  Position 3       812 non-null    object
dtypes: float64(1), object(14)
memory usage: 235.0+ KB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Jan 9', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,NaN,Dries De Boodt,Goalkeeper,"Jan 9, 1985",39,Belgium,Belgium,NaN,"1,86",-,NaN,Belgium,NaN,NaN,NaN
1,NaN,Charly Konstantinidis,Goalkeeper,"Jun 25, 1985",38,"Belgium, Greece",Belgium,Charleroi,"1,88",-,NaN,Belgium,Greece,NaN,NaN
2,NaN,Sven Van Ryckeghem,Goalkeeper,"Mar 18, 1985",39,Belgium,Belgium,Brugge,"1,85",-,NaN,Belgium,NaN,NaN,NaN
3,NaN,Logan Bailly,Goalkeeper,"Dec 27, 1985",38,Belgium,Belgium,Liege,"1,89",-,NaN,Belgium,NaN,NaN,NaN
4,38.0,Sammy Bossut,Goalkeeper,"Aug 11, 1985",38,Belgium,Belgium,Tielt,"1,86",-,NaN,Belgium,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,NaN,Dries De Boodt,Goalkeeper,"Jan 9, 1985",39,Belgium,Belgium,NaN,"1,86",-,NaN,Belgium,NaN,NaN,NaN,Jan 9,1985
1,NaN,Charly Konstantinidis,Goalkeeper,"Jun 25, 1985",38,"Belgium, Greece",Belgium,Charleroi,"1,88",-,NaN,Belgium,Greece,NaN,NaN,Jun 25,1985
2,NaN,Sven Van Ryckeghem,Goalkeeper,"Mar 18, 1985",39,Belgium,Belgium,Brugge,"1,85",-,NaN,Belgium,NaN,NaN,NaN,Mar 18,1985
3,NaN,Logan Bailly,Goalkeeper,"Dec 27, 1985",38,Belgium,Belgium,Liege,"1,89",-,NaN,Belgium,NaN,NaN,NaN,Dec 27,1985
4,38.0,Sammy Bossut,Goalkeeper,"Aug 11, 1985",38,Belgium,Belgium,Tielt,"1,86",-,NaN,Belgium,NaN,NaN,NaN,Aug 11,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985     58
1986     65
1987     79
1988     82
1989     74
1990     80
1991    100
1992    102
1993     98
1994    110
1995    100
1996    122
1997    120
1998    123
1999    125
2000    100
2001    122
2002    109
2003     84
2004     71
2005     73
Name: Name, dtype: int64